### ISSUE TITLE
Images & File Structure

### ISSUE THREAD

**Issue by hmontero1205** [belindaleebriggs/prj-rev-bwfs-dasmoto#2]
Your files are very organized and easy to look through. Nice touch downloading the images instead of linking them through the url provided. This lowers the probability that the client will not be able to access the images. Furthermore, you used the `alt` property in case that the images still cannot be loaded. I really that -- the missing img icon is really unattractive in my opinion.

**Comment by belindaleebriggs** [comment]
:-)
