### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by hmontero1205** [belindaleebriggs/prj-rev-bwfs-dasmoto#3]
I noticed that you have the following selectors:
`#brushes h2`, `#frames h2`, `#paint h2`.
Since you're using IDs, the selectors are inherently unique -- there is no need to add h2. 

Also, I usually caution against adding css properties to the body tag. Those properties will apply to everything in the body, sometimes resulting in unwanted effects when you try to add new elements that won't really have the same properties as the body.

**Comment by belindaleebriggs** [comment]
Thank you for this pointer.  This is very helpful, I've been "hacking" css for a while now and clearly have formed bad habits from now clearly understanding how things work!
